services:
  stats-server:
    build: stats/stats-server
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db

  stats-db:
    image: postgres:16.1
    container_name: postgress-db-container
    ports:
      - "7032:5432"
    environment:
      - POSTGRES_DB=stat
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

#  ewm-service:
#    ports:
#      - "8080:8080"

#  ewm-db:
#    image: postgres:16.1
